### PR TITLE
test(web): ID012_Responding_To_Friend_Requests

### PR DESCRIPTION
**Pull request by naziaC**
Closes: https://github.com/ECSE-428-Group-5-W-2023/OnCampus/issues/13

### CODE REVIEW

**Review by PierreMasselot1 — CHANGES_REQUESTED** [review]
the video ends on a cy wait and doesn't complete the full test

**Comment by naziaC** [comment]
> the video ends on a cy wait and doesn't complete the full test

I'm on mac and I can't even open the video 😭 I thought it was fine because the length matches up to the length on the cypress window, could u let me know what's the last action?

**Comment by PierreMasselot1** [comment]
@naziaC 
image

**Comment by PierreMasselot1** [comment]
yeah it's  weird the default player also doesn't like the vids on my end. I'll prob go through all of them to make sure that they are good before we submit

**Comment by naziaC** [comment]
@PierreMasselot1 ahh so I check that the info is gone (since we can't check on the db) so I'm guessing it ends on the wait before checking if the info is gone 

Should I just try rerecording?

Screen Shot 2023-04-02 at 10 07 44 PM

**Comment by PierreMasselot1** [comment]
you could maybe add another wait afterwards?

**Comment by naziaC** [comment]
@PierreMasselot1 is the video good this time? it should still end on a wait, but I think that it at least checks that the info is gone (?)

**Review by PierreMasselot1 — APPROVED** [review]
LGTM, seems like the video never shows the results so it's all good

**Pull request merged**
